version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "jromani-ds"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "jromani-ds"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "jromani-ds"
    labels:
      - "dependencies"
      - "terraform"
