name: Deploy Prod

on:
  push:
    branches: [master, main]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit # pragma: allowlist secret
    with:
      environment: prod
      api_service_name: mt-oil-api-prod
      tf_dir: infra/environments/prod
      frontend_bucket: ${{ vars.GCP_PROJECT_ID }}-mt-oil-dashboard
